### ISSUE TITLE
eine option für einen eq3 hack / Support 

### ISSUE THREAD

**Issue by cyclemat** [stefanbode/Sonoff-Tasmota#22]
kleine idee heute bekommen als ich youtube geguckt habe was hälst du von einem eq3 hack support ? 
https://www.youtube.com/watch?v=wjH21G1ghz0

schau dir das mal an würde dir auch eins zukommen lassen zum testen ;)

man könnte zb das magic home modul einfach drunter klemmen !
bzw ein schönen sleep Modus nutzen um günstig zu steuern

**Comment by stefanbode** [comment]
Hi, let me answer in English, so other subscribers can follow. In general a good idea and looks not be that complicated. Pulse width and length is easy to adjust and will work. Also start alway with 30 pulses to off and then send the temperature is also quite easy to implement. Now the tricky part: What is your use case?
If the ESP is always on and you just send the new temperature to the thermostat than this an easy task. This will also work nice with the increments because you may already know the current temperature. With deepsleep this is a completely different story. You need to store the "to be" temperature as a retained value into the MQTT server. With many clients it easy to process, but the ESP has some nasty limitations. on a subscribe to a topic you get only ONE message (if in good luck), sometimes nothing, but for sure not 2 or 3 messages if you e.g. subscribe to the wildcard topic like cmd/esp/#. I already tried to enhance the pubsublient but the problem seems to be deeper in the ESP espressif code.
Finally: There is no garantee that after a wakeup the temperature is read and set correctly because of the problem with the pubsubclient.
