### ISSUE TITLE
Question about garage door / gate

### ISSUE THREAD

**Issue by pszafer** [stefanbode/Sonoff-Tasmota#61]
Hello @stefanbode ,
I have Sonoff SV with standard Tasmota and I want it to use for opening/closing garage door and gate.
All people use reed switch to check if gate is open, but in such config we can't say to open gate to 30% etc.

I thought about timers, but sonoff has to give only short pulse to the gate to open it.

And my question is my second idea, which is to use somehow your shutter config. I guess it would be pretty easy for you to made another feature.

On Sonoff you have only one power but if you assume to start with close position, then user has to define
```
gateclosetime 30
gateopentime 40
```

If user has reed switch then you don't have to assume anything you just wait for gateclose and you are sure about the open/close state.

Thanks in advance!

**Comment by stefanbode** [comment]
Hi Pawel,
sorry I did not get it completely. First: your use case is to enhance garage open with 10%, 50% and so on instead of only open close. Right?
The garage motor has only ONE Relay that continues in the position until the end is reached or start and stop. Therefore only ONE pulse is sent for whatever action is required.
Why is 50% open so important for a garage door? Mine is eithe ropen or close but nothing inbetween

**Comment by pszafer** [comment]
My use case is more for front gate (going left/right). When I use remote I
can start it and stop it whenever I want so I can only get out with my bike.
It works with one relay - start right, stop, start left , stop etc.
